import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headrs from "./component/layout/Headre";
import { Toaster } from 'sonner';
import Footer from "./component/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className="w-full min-h-screen p-2 ">
        <Headrs/>
         <main>
           {children}
         </main>
        </div>
       <Toaster/>
       <footer>
        <Footer/>
        
       </footer>
      </body>
    </html>
  );
}
